# Use postgres/password user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    container_name: go-chat-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432